name: Bug
description: Reproducible bug report
title: "[BUG] "
labels: ["bug", "type:bug", "status:needs-review"]

body:
  - type: markdown
    attributes:
      value: "Use this issue to report a reproducible bug. Include clear steps and evidence."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: This template is always a bug report.
      options:
        - type:bug
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 4
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What happens and why is it a problem?"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: "What should happen?"
    validations:
      required: true
