name: Bug
description: Reporte de fallo reproducible
title: "[BUG] "
labels: ["bug", "status:needs-review"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      placeholder: "Qué ocurre y por qué es un problema."
    validations:
      required: true

  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para reproducir
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true

  - type: input
    id: entorno
    attributes:
      label: Entorno
      placeholder: "OS, navegador, versión, commit SHA, etc."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / capturas
      render: shell
      placeholder: "Pegar logs relevantes (sin secretos)."
    validations:
      required: false
