name: Style / Chore
description: Formatting, linting, cleanup, maintenance, minor refactor without functional changes
title: "[CHORE] "
labels: ["chore", "style", "type:chore", "status:needs-review"]

body:
  - type: markdown
    attributes:
      value: "Use this issue for non-functional changes: formatting, linting, cleanup, maintenance, and style-only updates."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the work type for this template.
      options:
        - type:chore
        - type:refactor
        - type:documentation
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 4
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What should be cleaned up or improved (no functional changes)."
    validations:
      required: true

  - type: textarea
    id: proposed_changes
    attributes:
      label: Proposed changes
      value: "- [ ] \n- [ ] \n- [ ] "
    validations:
      required: false

  - type: input
    id: tools
    attributes:
      label: Tools involved
      placeholder: "E.g., eslint, prettier, black, ruff, clang-format"
    validations:
      required: false

  - type: input
    id: references
    attributes:
      label: References
      placeholder: "Related issues, docs, or links"
    validations:
      required: false
