name: CI/CD
description: Pipeline, workflow, and deployment issues or improvements
title: "[CI/CD] "
labels: ["ci/cd", "type:feature", "status:needs-review"]

body:
  - type: markdown
    attributes:
      value: "Use this issue for CI/CD work: workflows, pipelines, build/test jobs, and deployment automation."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the CI/CD work type.
      options:
        - type:feature
        - type:bug
        - type:chore
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 4
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: "Which workflow/job fails, or what should be improved/created?"
    validations:
      required: true

  - type: input
    id: workflow_job
    attributes:
      label: Workflow / Job
      placeholder: "E.g., .github/workflows/ci.yml -> test"
    validations:
      required: true

  - type: input
    id: run_url
    attributes:
      label: Run link
      placeholder: "GitHub Actions run URL"
    validations:
      required: false

  - type: textarea
    id: main_error
    attributes:
      label: Main error
      render: shell
      placeholder: "Paste the key error."
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: Proposed change
      placeholder: "What would change and why?"
    validations:
      required: false
