name: CI/CD
description: Problemas o mejoras en pipelines, workflows y despliegue
title: "[CI/CD] "
labels: ["ci/cd", "status:needs-review"]
body:
  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      placeholder: "Qué workflow/job falla o qué se quiere mejorar."
    validations:
      required: true

  - type: input
    id: workflow
    attributes:
      label: Workflow / Job
      placeholder: "Ej: .github/workflows/ci.yml -> test"
    validations:
      required: true

  - type: input
    id: run_url
    attributes:
      label: Link al run
      placeholder: "URL del run de GitHub Actions"
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error principal
      render: shell
      placeholder: "Pegar el error clave."
    validations:
      required: true

  - type: textarea
    id: propuesta
    attributes:
      label: Propuesta de cambio
      placeholder: "Qué se cambiaría y por qué."
    validations:
      required: false
