name: Docs
description: Documentation changes
title: "[DOCS] "
labels: ["docs", "type:documentation", "status:needs-review"]
body:
  - type: markdown
    attributes:
      value: "Use this issue for documentation-only work."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Classify the type of change.
      options:
        - type:documentation
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 4
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to change in the documentation and why.
      placeholder: "Describe the goal and the reason for the change."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where the change should be made.
      placeholder: "E.g., README.md, docs/..., /api/docs, wiki..."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      value: "- [ ] Content is correct and up to date\n- [ ] Links work\n- [ ] Spelling and formatting reviewed"
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: "Links to related issues, specs, screenshots..."
    validations:
      required: false