name: Hotfix
description: Urgent production fix to be applied to main ASAP
title: "[HOTFIX] "
labels: ["hotfix", "type:bug", "status:needs-review"]

body:
  - type: markdown
    attributes:
      value: "Use this issue for urgent fixes that must be applied to main as soon as possible."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Hotfixes are always bug-related.
      options:
        - type:bug
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 0
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: Select the real-world impact of the incident.
      options:
        - "Production down"
        - "Core functionality broken"
        - "Service degraded"
        - "Minor incident but urgent"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      placeholder: "What is failing in production and since when?"
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Current mitigation / workaround
      placeholder: "Is there a temporary patch or alternative?"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if applicable)
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: false

  - type: textarea
    id: fix_plan
    attributes:
      label: Fix plan
      placeholder: "What will be changed, where, and why."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      value: "- [ ] Issue is reproducible\n- [ ] Fix is implemented\n- [ ] CI passes\n- [ ] Verified after deployment\n- [ ] No regressions introduced"
    validations:
      required: true

  - type: textarea
    id: branch_instructions
    attributes:
      label: Branch instructions
      description: Keep consistency with the branching strategy.
      value: "Create branch from main: hotfix/<scope>-<short-slug>"
    validations:
      required: true
