name: Task
description: Planned work item
title: "[TASK] "
labels: ["task", "type:feature", "status:needs-review"]

body:
  - type: markdown
    attributes:
      value: "Use this issue for planned work (not an urgent fix)."

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Classify the type of work for this task.
      options:
        - type:feature
        - type:refactor
        - type:chore
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority label to apply.
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
        - priority:backlog
      default: 4
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What we want to achieve.
      placeholder: "E.g., Implement X to enable Y."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is included and what is out of scope.
      placeholder: "- Includes...\n- Excludes..."
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Concrete steps to complete the task.
      value: "- [ ] \n- [ ] \n- [ ] "
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related PRs, docs, or issues.
      placeholder: "E.g., #123, link to documentation"
    validations:
      required: false
