name: Codacy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for outdated dependencies
      run: |
        python - <<'PY'
        import json, subprocess, os, sys
        out = subprocess.check_output([sys.executable, "-m", "pip", "list", "--outdated", "--format=json"])
        pkgs = json.loads(out.decode())
        summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
        lines = []
        if pkgs:
            print(f"{len(pkgs)} dependencias desactualizadas encontradas:")
            for p in pkgs:
                print(f"::warning title=Outdated dependency::{p['name']} {p['version']} -> {p['latest_version']} (latest: {p.get('latest_filetype','?')})")
            lines.append("### Dependencias desactualizadas\n")
            lines.append("| Paquete | Versión instalada | Última versión | Tipo |\n")
            lines.append("|---|---:|---:|---|\n")
            for p in pkgs:
                lines.append(f"| {p['name']} | {p['version']} | {p['latest_version']} | {p.get('latest_filetype','-')} |\n")
        else:
            print("No se han encontrado dependencias desactualizadas.")
            lines.append("✅ No se han encontrado dependencias desactualizadas.\n")

        if summary_path:
            with open(summary_path, "a", encoding="utf-8") as f:
                f.writelines(lines)
        PY

    - name: Upload coverage to Codacy
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pip install codacy-coverage
        coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
        coverage xml
        python-codacy-coverage -r coverage.xml
