name: Codacy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Solo en 3.12 para no duplicar avisos
    - name: Check for outdated dependencies
      if: matrix.python-version == '3.12'
      run: |
        python - <<'PY'
        import json, subprocess, os, sys
        out = subprocess.check_output([sys.executable, "-m", "pip", "list", "--outdated", "--format=json"])
        pkgs = json.loads(out.decode())
        summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
        lines = []
        if pkgs:
            print(f"{len(pkgs)} dependencias desactualizadas encontradas:")
            for p in pkgs:
                print(f"::warning title=Outdated dependency::{p['name']} {p['version']} -> {p['latest_version']} (latest: {p.get('latest_filetype','?')})")
            lines.append("### Dependencias desactualizadas\n")
            lines.append("| Paquete | Versión instalada | Última versión | Tipo |\n")
            lines.append("|---|---:|---:|---|\n")
            for p in pkgs:
                lines.append(f"| {p['name']} | {p['version']} | {p['latest_version']} | {p.get('latest_filetype','-')} |\n")
        else:
            print("No se han encontrado dependencias desactualizadas.")
            lines.append("No se han encontrado dependencias desactualizadas.\n")
        if summary_path:
            with open(summary_path, "a", encoding="utf-8") as f:
                f.writelines(lines)
        PY

    # Tests en todas las versiones para compatibilidad
    - name: Run tests (no coverage)
      if: matrix.python-version != '3.12'
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: |
        pytest app/modules/ --ignore-glob='*selenium*' -q

    # Solo en 3.12: cobertura + Codacy
    - name: Coverage & upload to Codacy (3.12 only)
      if: matrix.python-version == '3.12'
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pip install codacy-coverage
        coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
        coverage xml
        python-codacy-coverage -r coverage.xml

    # Análisis de seguridad con pip-audit (solo 3.12)
    - name: Security audit with pip-audit (SARIF + summary)
      if: matrix.python-version == '3.12'
      continue-on-error: true   # ← no falla el job si hay vulnerabilidades
      run: |
        pip install pip-audit
        # Genera SARIF para Code scanning
        pip-audit -f sarif -o pip-audit.sarif
        # Genera JSON para hacer un resumen legible
        pip-audit -f json -o pip-audit.json || true
        python - <<'PY'
        import json, os
        summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
        try:
            with open("pip-audit.json", "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            data = []
        vulns = [i for i in data if i.get("vulns")]
        lines = []
        if vulns:
            total = sum(len(i["vulns"]) for i in vulns)
            lines.append(f"### 🔒 pip-audit: {total} vulnerabilidades detectadas en {len(vulns)} paquetes\n")
            lines.append("| Paquete | Versión | Vulnerabilidad | Severidad | ID |\n")
            lines.append("|---|---:|---|---|---|\n")
            for item in vulns:
                name = item["name"]; version = item["version"]
                for v in item["vulns"]:
                    lines.append(f"| {name} | {version} | {v.get('description','-').splitlines()[0][:80]} | {v.get('severity','-')} | {v.get('id','-')} |\n")
            lines.append("\n> Revisa la pestaña **Security → Code scanning alerts** para detalles.\n")
        else:
            lines.append("pip-audit: no se han encontrado vulnerabilidades.\n")
        if summary_path:
            with open(summary_path, "a", encoding="utf-8") as f:
                f.writelines(lines)
        PY

    - name: Upload pip-audit SARIF to GitHub Security (3.12 only)
      if: matrix.python-version == '3.12'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: pip-audit.sarif
